export const basketballPlayers = [
  {
    name: 'Josh Pine',
    forGame: '16b',
    id: '2bp',
    amount: 3.5,
    price: 50,
    typeBet: '3 + attempts',
    sport: 'basketball-player',
    result: '',
    option: '',
  },
    {
      name: 'Jordan H.',
      forGame: '16b',
      id: '1bp',
      amount: 4.5,
      price: 70,
      typeBet: 'Points + Rebounds',
      sport: 'basketball-player',
      result: '',
      option: '',
    }
];

 export const basketballBets = [

  {
    sport: 'basketball',
    techTeam: 'Tech High Basketball (VB)',
    against: 'St. Helena',
    id: '16b',
    amount: 42.5,
    typeBet: 'Points',
    status: 'ended',
    option: '',
    result: 'under',
    price: 680,
    date: '11-19 19:30',
  },
  {
    sport: 'basketball',
    techTeam: 'Mike T.',
    against: 'Jake P.',
    id: '17b',
    amount: 0.5,
    typeBet: 'win',
    status: 'ended',
    option: '',
    result: 'over',
    price: 350,
    date: '11-15 19:30',
  },
    {
        sport: 'basketball',
        techTeam: 'Tech High Basketball (VB)',
        against: 'Victory Christian Academy',
        id: '10b',
        amount: 42.5,
        typeBet: 'Points',
        status: 'ended',
        option: '',
        result: 'over',
        price: 40,
        date: '1-11 18:30',
      },
      {
        sport: 'basketball',
        techTeam: 'Tech High Basketball (VB)',
        against: 'Credo',
        id: '9b',
        amount: 30.5,
        typeBet: 'Points',
        status: 'ended',
        option: '',
        result: 'under',
        price: 40,
        date: '11-15 18:30',
      },
      {
        sport: 'basketball',
        techTeam: 'Tech High Basketball (VB)',
        against: 'Roseland Collegiate Prep',
        id: '8b',
        amount: 30.5,
        typeBet: 'Points',
        status: 'ended',
        option: '',
        result: 'over',
        price: 40,
        date: '11-15 18:30',
      },
  ]
export const soccerBets  = [
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: `St. Bernard's`,
    id: '23s',
    amount: 1.5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'over',
    price: 600,
    date: '11-8 14:30',
  }, 
   
   {
    sport: 'soccer',
    techTeam: 'Trump * over',
    against: 'Kamala * under',
    id: '22s',
    amount: .5,
    typeBet: 'Vote',
    status: 'ended',
    option: '',
    result: 'over',
    price: 1200,
    date: '11-5 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'RCP',
    id: '21s',
    amount: .5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'over',
    price: 200,
    date: '10-30 16:30',
  }, 
   {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB) * senior night special',
    against: 'Credo',
    id: '20s',
    amount: .5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'under',
    price: 200,
    date: '10-30 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Sanoma Academy',
    id: '18s',
    amount: .5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'under',
    price: 300,
    date: '10-23 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'Calistoga',
    id: '19s',
    amount: 2.5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'under',
    price: 250,
    date: '10-23 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: '',
    id: '18s',
    amount: .5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'under',
    price: 150,
    date: '9-4 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Tomales',
    id: '18s',
    amount: .5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'under',
    price: 150,
    date: '9-4 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'Calistoga',
    id: '17s',
    amount: 1.5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'over',
    price: 250,
    date: '9-4 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Point Arena Soccer',
    id: '16s',
    amount: 1.5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'over',
    price: 150,
    date: '9-2 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'Mendocino',
    id: '15s',
    amount: 1.5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'under',
    price: 150,
    date: '9-2 16:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Credo',
    id: '13s',
    amount: .5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'over',
    price: 220,
    date: '9-27 18:30',
  }, 
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'Credo',
    id: '12s',
    amount: 1.5,
    typeBet: 'Goals',
    status: 'under',
    option: '',
    result: 'under',
    price: 320,
    date: '9-27 16:30',
  },
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VG)',
    against: 'Middle Town',
    id: '6s',
    amount: .5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'over',
    price: 20,
    date: '9-17 15:30',
  },
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Mendocino',
    id: '9s',
    amount: 1.5,
    typeBet: 'Goals',
    status: 'ended',
    option: '',
    result: 'under',
    price: 90,
    date: '9-11 16:30',
    info: 'home',
  },
  {
    sport: 'soccer',
    techTeam: 'Tech High Soccer (VB)',
    against: 'Roseland',
    id: '8s',
    amount: 1.5,
    typeBet: 'Goals',
    status: '',
    option: '',
    result: 'over',
    price: 200,
    date: '9-6 16:30',
  },

    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VB)',
      against: 'Point Arena Soccer',
      id: '7s',
      amount: 1.5,
      typeBet: 'Goals',
      status: '',
      option: '',
      result: 'under',
      price: 30,
      date: '8-30 16:30',
    },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Credo',
      id: '5s',
      amount: .5,
      typeBet: 'Goals',
      status: 'ended',
      option: '', // dont mess with this
      result: 'over',
      price: 145,
      date: '8-28 18:00',
    },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Middle Town',
      id: '2s',
      amount: 1.5,
      typeBet: 'Goals',
      status: 'ended',
      option: '',
      result: 'under',
      price: 20,
      date: '8-20 15:30',
    },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Willits',
      id: '1s',
      amount: 2.5,
      typeBet: 'Goals',
      status: 'ended',
      option: '',
      result: 'under',
      price: 75,
      date: '8-16 16:30',
    },
  ];


  export const volleyballBets = [
    {
      sport: 'volleyball',
      techTeam: 'Tech High Volleyball (VG)',
      against: 'Victory Christian Academy',
      id: '4v',
      amount: 1.5,
      typeBet: 'Set(s)',
      status: 'ended',
      option: '',
      result: 'over',
      price: 90,
      date: '9-9 18:00',
    },
    {
      sport: 'volleyball',
      techTeam: 'Tech High Volleyball (VG)',
      against: 'Elsie Allen ',
      id: '3v',
      amount: .5,
      typeBet: 'Set(s)',
      status: 'ended',
      option: '',
      result: 'over',
      price: 70,
      date: '9-5 18:00',
    },
    {
      sport: 'volleyball',
      techTeam: 'Tech High Volleyball (VG)',
      against: 'Anderson Valley Volleyball',
      id: '2v',
      amount: 1.5,
      typeBet: 'Set(s)',
      status: 'eneded',
      option: '',
      result: 'under',
      price: 20,
      date: '8-28 19:30',
    },
    {
    sport: 'volleyball',
    techTeam: 'Tech High Volleyball (VG)',
    against: 'Rio lindo Adventist Academy',
    id: '1v',
    amount: .5,
    typeBet: 'Set(s)',
    status: 'ended',
    option: '',
    result: 'over',
    price: 20,
    date: '8-28 18:00',
  },
];
export const schoolBets = [
  {
    id: '4sh',
    sport: 'school',
    price: 15,
    against: 'Jordan h.',
    typeBet: '3-points',
    status: '',
    option: '',
    result: 'under',
    amount: 2.5,
  },
  {
    id: '3sh',
    sport: 'school',
    price: 15,
    against: 'Kevin Bai',
    typeBet: 'Airballs',
    status: 'ended',
    option: '',
    result: 'under',
    amount: 11.5,
  },
  {
    id: '2sh',
    sport: 'school',
    price: 15,
    against: '6th per. Geomentry',
    typeBet: 'class avg.',
    status: '',
    option: '',
    result: '',
    amount: 88.5,
  },
  {
    id: '5sh',
    sport: 'school',
    price: 20,
    against: 'Mr weaver',
    typeBet: 'crashout',
    status: '',
    option: '',
    result: '',
    amount: .5,
    info: 'daily',
  },
]

const moneyBets = [
    {
      id: '1mm',
      sport: 'money',
      price: 25,
      against: 'daily 25',
      typeBet: 'money glicth',
      status: '',
      option: '',
      result: 'over',
      amount: .5,
    },
]

export let allBets = [...soccerBets, ...basketballBets, ...volleyballBets, ...schoolBets, ...basketballPlayers];
export let userBets = localStorage.getItem('userBets') ? JSON.parse(localStorage.getItem('userBets')) : [];
export let unfilteredAllBets = allBets;
