export const soccerBets  = [
    {
        sport: 'soccer',
        techTeam: 'Tech High Soccer (VG)',
        against: 'Rancho',
        id: '4s',
        amount: .5,
        typeBet: 'Goals',
        status: '',
        option: '', // dont mess with this
        result: '',
        price: 145,
        date: '8-29 11:00',
      },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Real Madrid',
      id: '3s',
      amount: .5,
      typeBet: 'Goals',
      status: '',
      option: '', // dont mess with this
      result: '',
      price: 145,
      date: '8-28 16:30',
    },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Middle Town',
      id: '2s',
      amount: 1.5,
      typeBet: 'Goals',
      status: 'ended',
      option: '',
      result: 'under',
      price: 20,
      date: '8-20 15:30',
    },
    {
      sport: 'soccer',
      techTeam: 'Tech High Soccer (VG)',
      against: 'Celtic',
      id: '1s',
      amount: 2.5,
      typeBet: 'Goals',
      status: 'ended',
      option: 'under',
      result: 'under',
      price: 75,
      date: '8-16 16:30',
    },
  ];

 export const basketballBets = [
    {
        sport: 'basketball',
        techTeam: 'Tech High Basketball (VB)',
        against: 'Celtic',
        id: '1b',
        amount: 42.5,
        typeBet: 'Points',
        status: 'ended',
        option: '',
        result: 'over',
        price: 40,
        date: '1-11 18:30',
      },
  ]