function generateRandomItems() {
    // List of 30 items
    const items = [
        "Costco (Bulk Groceries, Electronics) - (D)",
        "ExxonMobil (Fuel - 20 gallons) - (A)",
        "Panera Bread (Salad, Sandwich) - (C)",
        "Peet's Coffee (Dark Roast Coffee) - (A)",
        "Ebay (Collectibles, Fashion) - (D)",
        "Electricity Provider (Electric Bill) - (C)",
        "Gold's Gym (Fitness Classes) - (B)",
        "Train Ticket (Public Transportation) - (A)",
        "Jiffy Lube (Oil Change) - (C)",
        "Rite Aid (Prescription Medication) - (B)",
        "Nike Store (Running Shoes, Activewear) - (B)",
        "Microsoft Store (Laptop, Software) - (D)",
        "AT&T (Phone Bill) - (C)",
        "Verizon Fios (Internet Bill) - (C)",
        "Condo Association (Maintenance Fee) - (E)",
        "Booking.com (Hotel Reservation) - (D)",
        "Hyatt Regency (Hotel Stay - Executive Suite) - (E)",
        "American Airlines (Flight AA789, Seat 10B) - (D)",
        "DoorDash (Food Delivery) - (A)",
        "Street Parking (Parking Meter) - (A)",
        "Disney+ (Streaming Subscription) - (A)",
        "Wells Fargo (ATM Withdrawal - $75) - (A)",
        "Macy's (Cashback - $50) - (A)",
        "Amnesty International (Charity Donation - Human Rights) - (B)",
        "Mayo Clinic (Specialized Medical Procedure) - (E)",
        "Allstate (Insurance Premium - AUTO555) - (C)",
        "Mastercard (Credit Card Payment) - (D)",
        "FedLoan Servicing (Student Loan Payment) - (E)",
        "Stanford University (Tuition - Winter Quarter) - (E)",
        "Total Wine & More (Online Liquor Store - Wine, Whiskey) - (F)",
        "Ace Hardware (Home Improvement Supplies) - (C)",
        "Adidas (Sporting Goods, Sneakers) - (B)",
        "Vitamin Shoppe (Supplements, Protein Bars) - (B)",
        "Fitbit Store (Fitness Tracker, Accessories) - (D)",
        "Sony Store (PlayStation, Headset) - (D)",
        "Nikon (Camera Body, Lens) - (D)",
        "Fender (Acoustic Guitar) - (D)",
        "Chanel Boutique (Designer Handbag, Perfume) - (F)",
        "Cartier (Luxury Watch, Jewelry) - (F)",
        "Apple Store (iPad, Apple Pencil) - (D)",
        "Barnes & Noble (Books, E-reader) - (B)",
        "CitiBank (ATM Withdrawal - $100) - (A)",
        "HomeGoods (Cashback - $60) - (A)",
        "Greenpeace (Charity Donation - Environmental Conservation) - (B)",
        "Mayo Clinic (Surgery Procedure) - (E)",
        "Travelers Insurance (Insurance Premium - AUTO123) - (C)",
        "Discover (Credit Card Payment) - (D)",
        "Navient (Student Loan Payment) - (E)",
        "Caltech (Tuition - Spring Semester) - (E)",
        "Tequila Online Shop (Tequila - Reposado, Anejo) - (F)",
        "REI (Outdoor Gear, Camping Equipment) - (C)",
        "Under Armour (Athletic Apparel, Running Shoes) - (B)",
        "GNC (Protein Powder, Health Supplements) - (B)",
        "Fitbit Store (Smart Scale, Fitness Accessories) - (D)",
        "Canon (Camera Lens, Tripod) - (D)",
        "Gibson (Electric Guitar, Amplifier) - (D)",
        "Prada (Designer Handbag, Sunglasses) - (F)",
        "Tiffany & Co. (Diamond Earrings, Bracelet) - (F)",
        "Nintendo eShop (Video Game Purchase) - (D)",
        "Whole Foods Market (Organic Groceries, Fresh Produce) - (C)",
        "Chevron (Car Wash, Fuel - 15 gallons) - (A)",
        "Subway (Footlong Sandwich, Chips) - (A)",
        "Starbucks Reserve (Specialty Coffee Blend) - (B)",
        "Etsy (Handmade Jewelry, Art Prints) - (D)",
        "Water Company (Water Bill) - (C)",
        "Anytime Fitness (Gym Membership) - (B)",
        "City Bike Rental (Bike Ride) - (A)",
        "AutoZone (Car Battery, Wiper Blades) - (C)",
        "Walgreens (Beauty Products, Toothpaste) - (A)",
        "Forever 21 (Dress, Accessories) - (B)",
        "Apple Store (MacBook, AirPods Pro) - (D)",
        "T-Mobile (Phone Plan) - (C)",
        "Spectrum (Cable Bill) - (C)",
        "Luxury Condo Association (Maintenance Fee) - (E)",
        "Airbnb Experience (Guided Tour) - (D)",
        "Ritz-Carlton (Hotel Stay - Presidential Suite) - (F)",
        "United Airlines (Flight UA456, Seat 15A) - (D)",
        "UberEats (Food Delivery) - (A)",
        "Street Parking (Parking Meter) - (A)",
        "HBO Max (Streaming Subscription) - (A)",
        "Bank of America (ATM Withdrawal - $150) - (A)",
        "Best Buy (Cashback - $70) - (A)",
        "Save the Children (Charity Donation - Child Education) - (B)",
        "Mayo Clinic (Medical Checkup) - (E)",
        "Geico (Insurance Premium - AUTO555) - (C)",
        "Visa (Credit Card Payment) - (D)",
        "Navient (Student Loan Payment) - (E)",
        "MIT (Tuition - Fall Semester) - (E)",
        "BevMo! (Online Liquor Store - Vodka, Tequila) - (F)",
        "Lowe's (Home Improvement Supplies) - (C)",
        "Adidas (Sporting Goods, Soccer Cleats) - (B)",
        "Vitamin Shoppe (Supplements, Protein Bars) - (B)",
        "Fitbit Store (Fitness Tracker, Replacement Bands) - (D)",
        "Sony Store (PlayStation Controller, Games) - (D)",
        "Nikon (Camera Lens, Camera Bag) - (D)",
        "Taylor (Acoustic Guitar) - (D)",
        "Louis Vuitton (Designer Wallet, Belt) - (F)",
        "Tiffany & Co. (Diamond Ring, Necklace) - (F)",
        "Microsoft Store (Surface Pro, Wireless Mouse) - (D)",
        "Barnes & Noble (Books, Bookmarks) - (B)",
        "CitiBank (ATM Withdrawal - $200) - (A)",
        "HomeGoods (Cashback - $100) - (A)",
        "World Wildlife Fund (Charity Donation - Wildlife Conservation) - (B)",
        "Mayo Clinic (Specialized Medical Procedure) - (E)",
        "Allstate (Insurance Premium - AUTO777) - (C)",
        "Mastercard (Credit Card Payment) - (D)",
        "FedLoan Servicing (Student Loan Payment) - (E)",
        "Stanford University (Tuition - Winter Quarter) - (E)",
        "Total Wine & More (Online Liquor Store - Wine, Champagne) - (F)",
        "Ace Hardware (Home Improvement Supplies) - (C)",
        "Under Armour (Athletic Apparel, Running Shoes) - (B)",
        "GNC (Protein Powder, Fitness Equipment) - (B)",
        "Fitbit Store (Smartwatch, Charging Cable) - (D)",
        "Canon (Camera Tripod, Camera Bag) - (D)",
        "Gibson (Electric Guitar, Amplifier) - (D)",
        "Dior Boutique (Designer Handbag, Sunglasses) - (F)",
        "Harry Winston (Diamond Bracelet, Earrings) - (F)",
        "Nintendo eShop (Video Game Purchase) - (D)",
        "Whole Foods Market (Organic Groceries, Fresh Produce) - (C)",
        "Chevron (Car Wash, Fuel - 20 gallons) - (A)",
        "Subway (Footlong Sandwich, Cookies) - (A)",
        "Starbucks Reserve (Specialty Coffee Blend) - (B)",
        "Etsy (Handmade Jewelry, Art Prints) - (D)",
        "Water Company (Water Bill) - (C)",
        "Anytime Fitness (Gym Membership) - (B)",
        "Kroger (Fresh Produce, Dairy) - (A)",
        "Shell (Fuel - 12.5 gallons) - (A)",
        "Olive Garden (Pasta, Salad) - (C)",
        "Starbucks (Caramel Macchiato) - (A)",
        "Amazon (Electronics, Books) - (D)",
        "PG&E (Utility Bill) - (C)",
        "24 Hour Fitness (Platinum Gym Membership) - (C)",
        "Uber (Public Transportation - Downtown) - (A)",
        "Midas (Car Brake Replacement) - (C)",
        "CVS (Prescription Refill) - (B)",
        "H&M (Jeans, T-shirt) - (B)",
        "Best Buy (Smart TV) - (D)",
        "Verizon (Mobile Phone Bill) - (C)",
        "Comcast (Internet Bill) - (C)",
        "Zillow Rentals (Rent Payment) - (E)",
        "Airbnb (Accommodation - Jan 15-20) - (D)",
        "Hilton (Hotel Stay - Deluxe Suite) - (E)",
        "Delta (Airline Ticket - Flight DL123, Seat 25F) - (D)",
        "Lyft (Ride to Airport) - (A)",
        "ParkWhiz (Parking Fee - Lot C) - (A)",
        "Netflix (Premium Subscription) - (A)",
        "Chase Bank (ATM Withdrawal - $200) - (A)",
        "Target (Cashback - $30) - (A)",
        "Red Cross (Charity Donation - Disaster Relief) - (B)",
        "Mayo Clinic (Medical Bill - Invoice MED456) - (E)",
        "State Farm (Insurance Premium - AUTO789) - (C)",
        "American Express (Credit Card Payment) - (D)",
        "Sallie Mae (Student Loan Payment) - (E)",
        "Harvard University (Tuition - Spring Semester) - (E)",
        "Drizly (Online Liquor Store - Blue Label Johnnie Walker, Champagne",
        "City Bike Rental (Bike Ride) - (A)",
        "AutoZone (Car Battery, Wiper Blades) - (C)",
        "Walgreens (Beauty Products, Toothpaste) - (A)",
        "Forever 21 (Dress, Accessories) - (B)",
        "Apple Store (MacBook, AirPods Pro) - (D)",
        "T-Mobile (Phone Plan) - (C)",
        "Spectrum (Cable Bill) - (C)",
        "Luxury Condo Association (Maintenance Fee) - (E)",
        "Airbnb Experience (Guided Tour) - (D)",
        "Ritz-Carlton (Hotel Stay - Presidential Suite) - (F)",
        "United Airlines (Flight UA456, Seat 15A) - (D)",
        "UberEats (Food Delivery) - (A)",
        "Street Parking (Parking Meter) - (A)",
        "HBO Max (Streaming Subscription) - (A)",
        "Bank of America (ATM Withdrawal - $150) - (A)",
        "Best Buy (Cashback - $70) - (A)",
        "Save the Children (Charity Donation - Child Education) - (B)",
        "Mayo Clinic (Medical Checkup) - (E)",
        "Geico (Insurance Premium - AUTO555) - (C)",
        "Visa (Credit Card Payment) - (D)",
        "Navient (Student Loan Payment) - (E)",
        "MIT (Tuition - Fall Semester) - (E)",
        "BevMo! (Online Liquor Store - Vodka, Tequila) - (F)",
        "Lowe's (Home Improvement Supplies) - (C)",
        "Adidas (Sporting Goods, Soccer Cleats) - (B)",
        "Vitamin Shoppe (Supplements, Protein Bars) - (B)",
        "Fitbit Store (Fitness Tracker, Replacement Bands) - (D)",
        "Sony Store (PlayStation Controller, Games) - (D)",
        "Nikon (Camera Lens, Camera Bag) - (D)",
        "Taylor (Acoustic Guitar) - (D)",
        "Louis Vuitton (Designer Wallet, Belt) - (F)",
        "Tiffany & Co. (Diamond Ring, Necklace) - (F)",
        "Microsoft Store (Surface Pro, Wireless Mouse) - (D)",
        "Barnes & Noble (Books, Bookmarks) - (B)",
        "CitiBank (ATM Withdrawal - $200) - (A)",
        "HomeGoods (Cashback - $100) - (A)",
        "World Wildlife Fund (Charity Donation - Wildlife Conservation) - (B)",
        "Mayo Clinic (Specialized Medical Procedure) - (E)",
        "Allstate (Insurance Premium - AUTO777) - (C)",
        "Mastercard (Credit Card Payment) - (D)",
        "FedLoan Servicing (Student Loan Payment) - (E)",
        "Stanford University (Tuition - Winter Quarter) - (E)",
        "Total Wine & More (Online Liquor Store - Wine, Champagne) - (F)",
        "Ace Hardware (Home Improvement Supplies) - (C)",
        "Under Armour (Athletic Apparel, Running Shoes) - (B)",
        "GNC (Protein Powder, Fitness Equipment) - (B)",
        "Fitbit Store (Smartwatch, Charging Cable) - (D)",
        "Canon (Camera Tripod, Camera Bag) - (D)",
        "Gibson (Electric Guitar, Amplifier) - (D)",
        "Dior Boutique (Designer Handbag, Sunglasses) - (F)",
        "Harry Winston (Diamond Bracelet, Earrings) - (F)",
        "Nintendo eShop (Video Game Purchase) - (D)",
        "Whole Foods Market (Organic Groceries, Fresh Produce) - (C)",
        "Chevron (Car Wash, Fuel - 20 gallons) - (A)",
        "Subway (Footlong Sandwich, Cookies) - (A)",
        "Starbucks Reserve (Specialty Coffee Blend) - (B)",
        "Etsy (Handmade Jewelry, Art Prints) - (D)",
        "Water Company (Water Bill) - (C)",
        "Anytime Fitness (Gym Membership) - (B)",
        "City Bike Rental (Bike Ride) - (A)",
        "AutoZone (Car Battery, Wiper Blades) - (C)",
        "Walgreens (Beauty Products, Toothpaste) - (A)",
        "Forever 21 (Dress, Accessories) - (B)",
        "Apple Store (MacBook, AirPods Pro) - (D)",
        "T-Mobile (Phone Plan) - (C)",
        "Spectrum (Cable Bill) - (C)",
        "Luxury Condo Association (Maintenance Fee) - (E)",
        "Airbnb Experience (Guided Tour) - (D)",
        "Ritz-Carlton (Hotel Stay - Presidential Suite) - (F)",
        "United Airlines (Flight UA456, Seat 15A) - (D)",
        "UberEats (Food Delivery) - (A)",
        "Street Parking (Parking Meter) - (A)",
        "HBO Max (Streaming Subscription) - (A)",
        "Bank of America (ATM Withdrawal - $150) - (A)",
        "Best Buy (Cashback - $70)",
        "Chevron (Fuel - 15 gallons) - (A)",
        "Chipotle (Burrito, Guacamole) - (C)",
        "Dunkin' (Iced Coffee, Donuts) - (A)",
        "Etsy (Handmade Crafts, Home Decor) - (D)",
        "Water Company (Water Bill) - (C)",
        "Planet Fitness (Basic Gym Membership) - (B)",
        "City Bus Fare - (A)",
        "AutoZone (Car Battery, Oil Filter) - (C)",
        "Walgreens (Over-the-Counter Medicine) - (B)",
        "Forever 21 (Dress, Accessories) - (B)",
        "Apple Store (iPhone, AirPods) - (D)",
        "T-Mobile (Phone Plan) - (C)",
        "Spectrum (Cable Bill) - (C)",
        "Apartment Complex (Rent Payment) - (E)",
        "VRBO (Vacation Rental) - (D)",
        "Marriott (Hotel Stay - Standard Room) - (E)",
        "Southwest Airlines (Flight SW456, Seat 30A) - (D)",
        "UberEats (Food Delivery) - (A)",
        "Parking Garage (Hourly Parking) - (A)",
        "Hulu (Streaming Subscription) - (A)",
        "Bank of America (ATM Withdrawal - $50) - (A)",
        "Best Buy (Cashback - $40) - (A)",
        "UNICEF (Charity Donation - Children's Education) - (B)",
        "Mayo Clinic (Medical Checkup) - (E)",
        "Geico (Insurance Premium - AUTO987) - (C)",
        "Visa (Credit Card Payment) - (D)",
        "Navient (Student Loan Payment) - (E)",
        "MIT (Tuition - Fall Semester) - (E)",
        "BevMo! (Online Liquor Store - Champagne, Vodka) - (F)",
        "Home Depot (DIY Supplies, Tools) - (C)",
        "Lululemon (Athletic Apparel, Yoga Mat) - (B)",
        "GNC (Vitamins, Protein Powder) - (B)",
        "Samsung Store (Smartwatch, Galaxy Buds) - (D)",
        "Bose (Noise-Canceling Headphones) - (D)",
        "Canon (Camera, Lens) - (D)",
        "Gibson (Electric Guitar) - (D)",
        "Louis Vuitton (Designer Handbag, Sunglasses) - (F)",
        "Tiffany & Co. (Diamond Necklace, Bracelet) - (F)"
        
    ];

    // Shuffle the items array
    for (let i = items.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [items[i], items[j]] = [items[j], items[i]];
    }

    // Apply different items to each element with the class "randomItems"
    const itemElements = document.querySelectorAll('.randomItems');
    itemElements.forEach((element) => {
      // Create a list item for each item in the shuffled array
      const listItem = document.createElement('l');
      listItem.textContent = items.pop(); // Get and remove the last item from the shuffled array
      element.appendChild(listItem);
    });
  }

  // Call the function when the page loads
  generateRandomItems();