export const LEVEL_MODES = {
  easy: {
    id: "easy",
    label: "Easy",
    summary: "Full assists — borders, exact distances, autocomplete, unlimited guesses.",
    looseBorders: false,
    roundDistance: 0,
    showDistances: true,
    autocomplete: true,
    maxGuesses: null,
    zones: null,
    flyGlobe: true,
    grayFill: false,
    pureDistance: false,
  },
  medium: {
    id: "medium",
    label: "Medium",
    summary: "Loose borders, distances rounded to 500 km.",
    looseBorders: true,
    roundDistance: 500,
    showDistances: true,
    autocomplete: true,
    maxGuesses: null,
    zones: null,
    flyGlobe: true,
    grayFill: false,
    pureDistance: false,
  },
  hard: {
    id: "hard",
    label: "Hard",
    summary: "Medium rules plus autocomplete, distances shown — 8 guesses only.",
    looseBorders: true,
    roundDistance: 500,
    showDistances: true,
    autocomplete: true,
    maxGuesses: 8,
    zones: null,
    flyGlobe: true,
    grayFill: false,
    pureDistance: false,
  },
  xtra: {
    id: "xtra",
    label: "Xtra",
    summary: "Hard rules plus 5 guesses, 3 distance zones, no globe fly-to.",
    looseBorders: true,
    roundDistance: 500,
    showDistances: true,
    autocomplete: true,
    maxGuesses: 5,
    zones: 3,
    flyGlobe: false,
    grayFill: false,
    pureDistance: false,
  },
  xtra2: {
    id: "xtra2",
    label: "Xtra II",
    summary: "Pure distance numbers only — guessed countries fill gray.",
    looseBorders: true,
    roundDistance: 500,
    showDistances: true,
    autocomplete: true,
    maxGuesses: 5,
    zones: 3,
    flyGlobe: false,
    grayFill: true,
    pureDistance: true,
  },
};

export const LEVEL_ORDER = ["easy", "medium", "hard", "xtra", "xtra2"];

export function getLevelMode(id) {
  return LEVEL_MODES[id] ?? LEVEL_MODES.easy;
}
